HEADERS += ../submodules/BaseMap/core/coordinatetranslator.h \
    ../submodules/BaseMap/core/distanceconverters.h \
    ../submodules/BaseMap/core/gps_position.h \
    ../submodules/BaseMap/core/idistanceconverter.h \
    ../submodules/BaseMap/core/mapfile.h \
    ../submodules/BaseMap/core/urlconverter.h \
    ../submodules/BaseMap/core/zoomleveldistances.h \
    ../submodules/BaseMap/geometries/circlepoint.h \
    ../submodules/BaseMap/geometries/fixedimageoverlay.h \
    ../submodules/BaseMap/geometries/pelengbase.h \
    ../submodules/BaseMap/geometries/place.h \
    ../submodules/BaseMap/geometries/region.h \
    ../submodules/BaseMap/geometries/rpp.h \
    ../submodules/BaseMap/geometries/rpplabeled.h \
    ../submodules/BaseMap/core/geometrylayer.h \
    ../submodules/BaseMap/core/imagemanager.h \
    ../submodules/BaseMap/core/layer.h \
    ../submodules/BaseMap/core/layermanager.h \
    ../submodules/BaseMap/core/mapcontrol.h \
    ../submodules/BaseMap/core/mapempty.h \
    ../submodules/BaseMap/core/maplayer.h \
    ../submodules/BaseMap/core/maploader.h \
    ../submodules/BaseMap/core/maplocalindexfile.h \
    ../submodules/BaseMap/core/maplocalpath.h \
    ../submodules/BaseMap/core/maplocalworker.h \
    ../submodules/BaseMap/core/mapnetwork.h \
    ../submodules/BaseMap/core/mapnetworkclient.h \
    ../submodules/BaseMap/core/mapnetworkfactory.h \
    ../submodules/BaseMap/extentions/checkablemapextention.h \
    ../submodules/BaseMap/extentions/citylabelsmapextention.h \
    ../submodules/BaseMap/extentions/coordinatenetmapextention.h \
    ../submodules/BaseMap/extentions/createimagemapextention.h \
    ../submodules/BaseMap/extentions/createorientedrppmapextention.h \
    ../submodules/BaseMap/extentions/createpelengmapextention.h \
    ../submodules/BaseMap/extentions/createplacemapextention.h \
    ../submodules/BaseMap/extentions/createregionmapextention.h \
    ../submodules/BaseMap/extentions/createrppmapextention.h \
    ../submodules/BaseMap/extentions/createsectormapextention.h \
    ../submodules/BaseMap/extentions/cursorposmapextention.h \
    ../submodules/BaseMap/extentions/ellipseselectionmapextention.h \
    ../submodules/BaseMap/extentions/geometryconnectormapextention.h \
    ../submodules/BaseMap/extentions/geometrycreatormapextention.h \
    ../submodules/BaseMap/extentions/geometryinfomapextention.h \
    ../submodules/BaseMap/extentions/geometryprocessormapextention.h \
    ../submodules/BaseMap/extentions/layerswitchmapextention.h \
    ../submodules/BaseMap/extentions/lengthmeasuremapextention.h \
    ../submodules/BaseMap/extentions/mapextention.h \
    ../submodules/BaseMap/extentions/mapextentionmanager.h \
    ../submodules/BaseMap/extentions/objectmovemapextention.h \
    ../submodules/BaseMap/extentions/persistentmapextention.h \
    ../submodules/BaseMap/extentions/rectangleselectionmapextention.h \
    ../submodules/BaseMap/extentions/scrollzoommapextention.h \
    ../submodules/BaseMap/extentions/sectorselectionmapextention.h \
    ../submodules/BaseMap/extentions/selectionmapextention.h \
    ../submodules/BaseMap/extentions/selectormapextention.h \
    ../submodules/BaseMap/extentions/showallmapextention.h \
    ../submodules/BaseMap/extentions/showgeometrymapextention.h \
    ../submodules/BaseMap/extentions/zoominmapextention.h \
    ../submodules/BaseMap/extentions/zoomoutmapextention.h \
    ../submodules/BaseMap/geometries/citylabel.h \
    ../submodules/BaseMap/geometries/curve.h \
    ../submodules/BaseMap/geometries/geometry.h \
    ../submodules/BaseMap/geometries/image.h \
    ../submodules/BaseMap/geometries/linestring.h \
    ../submodules/BaseMap/geometries/peleng.h \
    ../submodules/BaseMap/geometries/point.h \
    ../submodules/BaseMap/geometries/sector.h \
    ../submodules/BaseMap/geometries/staticgeometry.h \
    ../submodules/BaseMap/adapters/tilemapadapter.h \
    ../submodules/BaseMap/adapters/mapadapter.h \
    ../submodules/BaseMap/adapters/localmapadapter.h \
    ../submodules/BaseMap/adapters/emptymapadapter.h
SOURCES += ../submodules/BaseMap/adapters/emptymapadapter.cpp \
    ../submodules/BaseMap/adapters/localmapadapter.cpp \
    ../submodules/BaseMap/adapters/mapadapter.cpp \
    ../submodules/BaseMap/adapters/tilemapadapter.cpp \
    ../submodules/BaseMap/core/coordinatetranslator.cpp \
    ../submodules/BaseMap/core/distanceconverters.cpp \
    ../submodules/BaseMap/core/geometrylayer.cpp \
    ../submodules/BaseMap/core/gps_position.cpp \
    ../submodules/BaseMap/core/imagemanager.cpp \
    ../submodules/BaseMap/core/layer.cpp \
    ../submodules/BaseMap/core/layermanager.cpp \
    ../submodules/BaseMap/core/mapcontrol.cpp \
    ../submodules/BaseMap/core/maplayer.cpp \
    ../submodules/BaseMap/core/maplocalindexfile.cpp \
    ../submodules/BaseMap/core/maplocalpath.cpp \
    ../submodules/BaseMap/core/maplocalworker.cpp \
    ../submodules/BaseMap/core/mapnetwork.cpp \
    ../submodules/BaseMap/core/mapnetworkclient.cpp \
    ../submodules/BaseMap/core/mapnetworkfactory.cpp \
    ../submodules/BaseMap/core/zoomleveldistances.cpp \
    ../submodules/BaseMap/extentions/checkablemapextention.cpp \
    ../submodules/BaseMap/extentions/citylabelsmapextention.cpp \
    ../submodules/BaseMap/extentions/coordinatenetmapextention.cpp \
    ../submodules/BaseMap/extentions/createimagemapextention.cpp \
    ../submodules/BaseMap/extentions/createorientedrppmapextention.cpp \
    ../submodules/BaseMap/extentions/createpelengmapextention.cpp \
    ../submodules/BaseMap/extentions/createplacemapextention.cpp \
    ../submodules/BaseMap/extentions/createregionmapextention.cpp \
    ../submodules/BaseMap/extentions/createrppmapextention.cpp \
    ../submodules/BaseMap/extentions/createsectormapextention.cpp \
    ../submodules/BaseMap/extentions/cursorposmapextention.cpp \
    ../submodules/BaseMap/extentions/ellipseselectionmapextention.cpp \
    ../submodules/BaseMap/extentions/geometryconnectormapextention.cpp \
    ../submodules/BaseMap/extentions/geometrycreatormapextention.cpp \
    ../submodules/BaseMap/extentions/geometryinfomapextention.cpp \
    ../submodules/BaseMap/extentions/geometryprocessormapextention.cpp \
    ../submodules/BaseMap/extentions/layerswitchmapextention.cpp \
    ../submodules/BaseMap/extentions/lengthmeasuremapextention.cpp \
    ../submodules/BaseMap/extentions/mapextention.cpp \
    ../submodules/BaseMap/extentions/mapextentionmanager.cpp \
    ../submodules/BaseMap/extentions/objectmovemapextention.cpp \
    ../submodules/BaseMap/extentions/persistentmapextention.cpp \
    ../submodules/BaseMap/extentions/rectangleselectionmapextention.cpp \
    ../submodules/BaseMap/extentions/scrollzoommapextention.cpp \
    ../submodules/BaseMap/extentions/sectorselectionmapextention.cpp \
    ../submodules/BaseMap/extentions/selectionmapextention.cpp \
    ../submodules/BaseMap/extentions/selectormapextention.cpp \
    ../submodules/BaseMap/extentions/showallmapextention.cpp \
    ../submodules/BaseMap/extentions/showgeometrymapextention.cpp \
    ../submodules/BaseMap/extentions/zoominmapextention.cpp \
    ../submodules/BaseMap/extentions/zoomoutmapextention.cpp \
    ../submodules/BaseMap/geometries/circlepoint.cpp \
    ../submodules/BaseMap/geometries/citylabel.cpp \
    ../submodules/BaseMap/geometries/curve.cpp \
    ../submodules/BaseMap/geometries/fixedimageoverlay.cpp \
    ../submodules/BaseMap/geometries/geometry.cpp \
    ../submodules/BaseMap/geometries/image.cpp \
    ../submodules/BaseMap/geometries/linestring.cpp \
    ../submodules/BaseMap/geometries/peleng.cpp \
    ../submodules/BaseMap/geometries/pelengbase.cpp \
    ../submodules/BaseMap/geometries/place.cpp \
    ../submodules/BaseMap/geometries/point.cpp \
    ../submodules/BaseMap/geometries/region.cpp \
    ../submodules/BaseMap/geometries/rpp.cpp \
    ../submodules/BaseMap/geometries/rpplabeled.cpp \
    ../submodules/BaseMap/geometries/sector.cpp \
    ../submodules/BaseMap/geometries/staticgeometry.cpp
